// Pure transforms behind withMetaVR.js, kept free of @expo/config-plugins so
// the root test suite can run them without the reference app's node_modules.

/**
 * Maven BOM that pins the MetaVRX Layout SDK AARs. It lists
 * com.meta.metavrx.layout:layout-react-compat:1.0.0 and
 * layout-window-react-compat:1.0.0, the artifacts that
 * @metavr/layout-compat@1.0.0 and @metavr/layout-window-compat@1.0.0 pull in
 * through `api(...)` in their android/build.gradle.kts.
 * https://repo1.maven.org/maven2/com/meta/metavrx/metavrx-bom/1.2026.0.0/
 */
const METAVRX_BOM = 'com.meta.metavrx:metavrx-bom:1.2026.0.0'

const BOM_LINE = `    implementation platform("${METAVRX_BOM}")`

/**
 * Adds the MetaVRX BOM to the app module's top-level `dependencies` block.
 * Idempotent, so repeated `expo prebuild` runs leave one line.
 *
 * @param {string} contents android/app/build.gradle
 * @returns {string}
 */
function addMetavrxBom(contents) {
  if (contents.includes(METAVRX_BOM)) {
    return contents
  }
  const block = /^dependencies\s*\{[ \t]*\n/m
  const match = block.exec(contents)
  if (match === null) {
    throw new Error(
      'withMetaVR: android/app/build.gradle has no top-level `dependencies {` block to add the MetaVRX BOM to',
    )
  }
  const at = match.index + match[0].length
  return `${contents.slice(0, at)}${BOM_LINE}\n${contents.slice(at)}`
}

/**
 * Entries @reactvision/react-viro 3.0.3 writes into the main manifest when
 * `android.xRMode` includes "QUEST" (plugins/withViroAndroid.ts, the
 * `activeXrModes.includes("QUEST")` block and the VRActivity mod). Viro's
 * plugin is not flavor-aware, so without this the `mobile` flavor ships them.
 */
const QUEST_ONLY_FEATURES = [
  'android.hardware.vr.headtracking',
  'oculus.software.handtracking',
  'com.oculus.feature.PASSTHROUGH',
  'oculus.software.eye_tracking',
]

const QUEST_ONLY_PERMISSIONS = [
  'horizonos.permission.HAND_TRACKING',
  'com.oculus.permission.EYE_TRACKING',
  'horizonos.permission.USE_ANCHOR_API',
  'com.oculus.permission.USE_SCENE',
  'horizonos.permission.HEADSET_CAMERA',
  'horizonos.permission.IMPORT_EXPORT_IOT_MAP_DATA',
  'com.oculus.permission.BOUNDARY_VISIBILITY',
]

const QUEST_ONLY_ACTIVITIES = ['.VRActivity']

const QUEST_ONLY_METADATA = ['com.oculus.supportedDevices']

/**
 * The `mobile` flavor manifest. Flavor manifests merge over main, and
 * `tools:node="remove"` drops the matching element from the merged result,
 * including copies that come from library AARs.
 *
 * @returns {string}
 */
function mobileFlavorManifest() {
  const features = QUEST_ONLY_FEATURES.map(
    (name) => `  <uses-feature android:name="${name}" tools:node="remove" />`,
  )
  const permissions = QUEST_ONLY_PERMISSIONS.map(
    (name) => `  <uses-permission android:name="${name}" tools:node="remove" />`,
  )
  const activities = QUEST_ONLY_ACTIVITIES.map(
    (name) => `    <activity android:name="${name}" tools:node="remove" />`,
  )
  const metadata = QUEST_ONLY_METADATA.map(
    (name) => `    <meta-data android:name="${name}" tools:node="remove" />`,
  )
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    '<!-- Generated by plugins/withMetaVR.js. Keeps Quest-only entries out of the mobile flavor. -->',
    '<manifest xmlns:android="http://schemas.android.com/apk/res/android"',
    '  xmlns:tools="http://schemas.android.com/tools">',
    ...features,
    ...permissions,
    '  <application>',
    ...activities,
    ...metadata,
    '  </application>',
    '</manifest>',
    '',
  ].join('\n')
}

module.exports = {
  METAVRX_BOM,
  QUEST_ONLY_ACTIVITIES,
  QUEST_ONLY_FEATURES,
  QUEST_ONLY_METADATA,
  QUEST_ONLY_PERMISSIONS,
  addMetavrxBom,
  mobileFlavorManifest,
}
